# ==========================================
# Time Entry Filter Validation Lab
# ATR Filter Validation v1
#
# Save path:
# src/filter_validation/atr_filter_validation_v1.py
#
# Purpose:
# - Validate ATR filter candidates using trade logs generated by Event Filter v2.
# - Compare ATR OFF / P60 / P65 / P70 / P75 / Lookback 250/500/750.
# - Compare mainly:
#   1) Current Event: Candidate A date_all_day
#   2) Candidate Event: Candidate C hybrid policy
#
# Required input:
# - Run event_filter_validation_v2.py first.
# - Keep this file available in Colab:
#   /content/EventFilter_V2_TradeLogs.csv
#
# Outputs:
# - /content/ATRFilter_Comparison_Summary_v1.csv
# - /content/ATRFilter_Strategy_Summary_v1.csv
# - /content/ATRFilter_Pair_Summary_v1.csv
# - /content/ATRFilter_Rejects_v1.csv
# - /content/ATRFilter_Allowed_Trades_v1.csv
# ==========================================

from google.colab import drive
import pandas as pd
import numpy as np
import glob
import os

# ==========================================
# 0. CONFIG
# ==========================================

drive.mount('/content/drive')

TRADE_LOG_PATH = '/content/EventFilter_V2_TradeLogs.csv'
OUTPUT_DIR = '/content'

# Event scenarios to compare.
# Candidate B can be added if needed.
EVENT_SCENARIOS_TO_TEST = [
    'CANDIDATE_A_DATE_ALL_DAY_CURRENT',
    'CANDIDATE_C_HYBRID_POLICY',
]

PAIR_DATA_PATTERNS = {
    'EJ': 'eurjpy_m1',
    'GJ': 'gbpjpy_m1',
    'AJ': 'audjpy_m1',
    'UJ': 'usdjpy_m1',
    'EA': 'euraud_m1',
    'GA': 'gbpaud_m1',
    'AU': 'audusd_m1',
}

# ATR settings: H1 ATR(14), closed bar, percentile threshold.
ATR_TIMEFRAME = '1H'
ATR_PERIOD = 14
ATR_USE_CLOSED_BAR = True

# Percentile distribution policy.
# True: threshold uses lookback bars before current ATR bar.
# False: threshold includes current ATR bar in the lookback window.
ATR_THRESHOLD_EXCLUDE_CURRENT = True

ATR_TEST_CONDITIONS = [
    {'Condition': 'ATR_OFF', 'UseATR': False, 'Percentile': None, 'Lookback': None},
    {'Condition': 'ATR_P60_LB500', 'UseATR': True, 'Percentile': 60.0, 'Lookback': 500},
    {'Condition': 'ATR_P65_LB500', 'UseATR': True, 'Percentile': 65.0, 'Lookback': 500},
    {'Condition': 'ATR_P70_LB500_CURRENT', 'UseATR': True, 'Percentile': 70.0, 'Lookback': 500},
    {'Condition': 'ATR_P75_LB500', 'UseATR': True, 'Percentile': 75.0, 'Lookback': 500},
    {'Condition': 'ATR_P70_LB250', 'UseATR': True, 'Percentile': 70.0, 'Lookback': 250},
    {'Condition': 'ATR_P70_LB750', 'UseATR': True, 'Percentile': 70.0, 'Lookback': 750},
]

# ==========================================
# 1. Data loading
# ==========================================

def load_m1_data(pair_key):
    pattern = PAIR_DATA_PATTERNS[pair_key]
    files = glob.glob(f'/content/drive/MyDrive/MT5 data/*{pattern}*.csv')

    if not files:
        raise FileNotFoundError(f'M1 data file not found for {pair_key}: pattern={pattern}')

    df_list = []

    for f in files:
        tmp = pd.read_csv(
            f,
            names=['Date', 'Time', 'Open', 'High', 'Low', 'Close', 'TickVol', 'Vol', 'Spread'],
            header=0,
            sep='\t'
        )
        df_list.append(tmp)

    df = pd.concat(df_list, ignore_index=True)
    df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])

    # Original validation code assumes source data timezone = Europe/Helsinki, then converts to JST.
    df['Datetime'] = (
        df['Datetime']
        .dt.tz_localize('Europe/Helsinki')
        .dt.tz_convert('Asia/Tokyo')
        .dt.tz_localize(None)
    )

    df = df.drop_duplicates(subset=['Datetime'])
    df = df.sort_values('Datetime')
    df = df.reset_index(drop=True)

    print(f"✅ Loaded {pair_key}: {len(df):,} bars / {df['Datetime'].min()} 〜 {df['Datetime'].max()}")

    return df


def load_trade_log():
    if not os.path.exists(TRADE_LOG_PATH):
        raise FileNotFoundError(
            f'{TRADE_LOG_PATH} not found. Run event_filter_validation_v2.py first.'
        )

    df = pd.read_csv(TRADE_LOG_PATH)
    df['EntryTime'] = pd.to_datetime(df['EntryTime'])
    df['CloseTime'] = pd.to_datetime(df['CloseTime'])

    df = df[df['Scenario'].isin(EVENT_SCENARIOS_TO_TEST)].copy()
    df = df.reset_index(drop=True)

    print(f'✅ Loaded trade log: {len(df):,} trades')
    print('Scenarios:', sorted(df['Scenario'].unique()))

    return df

# ==========================================
# 2. ATR calculation
# ==========================================

def calc_atr_h1_from_m1(df_m1):
    df = df_m1[['Datetime', 'Open', 'High', 'Low', 'Close']].copy()
    df = df.set_index('Datetime')

    h1 = df.resample(ATR_TIMEFRAME, label='left', closed='left').agg({
        'Open': 'first',
        'High': 'max',
        'Low': 'min',
        'Close': 'last',
    })

    h1 = h1.dropna().copy()

    prev_close = h1['Close'].shift(1)
    tr1 = h1['High'] - h1['Low']
    tr2 = (h1['High'] - prev_close).abs()
    tr3 = (h1['Low'] - prev_close).abs()

    h1['TR'] = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

    # Wilder-like smoothing is common, but EA implementation may use iATR.
    # MT5 iATR uses Wilder smoothing. ewm(alpha=1/period) is a close approximation.
    h1['ATR'] = h1['TR'].ewm(alpha=1 / ATR_PERIOD, adjust=False, min_periods=ATR_PERIOD).mean()
    h1 = h1.dropna(subset=['ATR']).copy()

    h1['AtrBarTime'] = h1.index
    h1 = h1.reset_index(drop=True)

    return h1


def build_atr_cache(pair_keys):
    cache = {}

    for pair in pair_keys:
        df_m1 = load_m1_data(pair)
        h1 = calc_atr_h1_from_m1(df_m1)
        cache[pair] = h1
        print(f"✅ Built H1 ATR for {pair}: {len(h1):,} bars")

    return cache


def get_closed_atr_bar_time(entry_time):
    entry_time = pd.Timestamp(entry_time)
    floored = entry_time.floor('h')

    if ATR_USE_CLOSED_BAR:
        return floored - pd.Timedelta(hours=1)

    return floored


def get_atr_decision(pair, entry_time, condition, atr_cache):
    if not condition['UseATR']:
        return {
            'PassATR': True,
            'AtrValue': np.nan,
            'AtrThreshold': np.nan,
            'AtrPercentile': np.nan,
            'AtrLookback': np.nan,
            'AtrBarTime': pd.NaT,
            'AtrReason': 'ATR_OFF'
        }

    percentile = condition['Percentile']
    lookback = int(condition['Lookback'])
    h1 = atr_cache[pair]
    atr_bar_time = get_closed_atr_bar_time(entry_time)

    # exact H1 start match
    matches = h1.index[h1['AtrBarTime'] == atr_bar_time].tolist()

    if not matches:
        return {
            'PassATR': False,
            'AtrValue': np.nan,
            'AtrThreshold': np.nan,
            'AtrPercentile': percentile,
            'AtrLookback': lookback,
            'AtrBarTime': atr_bar_time,
            'AtrReason': 'ATR_BAR_NOT_FOUND'
        }

    idx = matches[0]
    current_atr = h1.loc[idx, 'ATR']

    if ATR_THRESHOLD_EXCLUDE_CURRENT:
        start = idx - lookback
        end = idx
    else:
        start = idx - lookback + 1
        end = idx + 1

    if start < 0:
        return {
            'PassATR': False,
            'AtrValue': current_atr,
            'AtrThreshold': np.nan,
            'AtrPercentile': percentile,
            'AtrLookback': lookback,
            'AtrBarTime': atr_bar_time,
            'AtrReason': 'INSUFFICIENT_LOOKBACK'
        }

    window = h1.loc[start:end - 1, 'ATR'].dropna().values

    if len(window) < lookback:
        return {
            'PassATR': False,
            'AtrValue': current_atr,
            'AtrThreshold': np.nan,
            'AtrPercentile': percentile,
            'AtrLookback': lookback,
            'AtrBarTime': atr_bar_time,
            'AtrReason': 'INSUFFICIENT_LOOKBACK'
        }

    threshold = float(np.percentile(window, percentile))
    passed = bool(current_atr >= threshold)

    return {
        'PassATR': passed,
        'AtrValue': current_atr,
        'AtrThreshold': threshold,
        'AtrPercentile': percentile,
        'AtrLookback': lookback,
        'AtrBarTime': atr_bar_time,
        'AtrReason': 'PASS' if passed else 'ATR_REJECT'
    }

# ==========================================
# 3. Summary helpers
# ==========================================

def calc_summary(df, label):
    if df.empty:
        return {
            'Label': label,
            'Trades': 0,
            'WinRate': np.nan,
            'PF': np.nan,
            'TotalPips': 0,
            'MaxDD': 0,
            'RoMD': np.nan,
            'AvgPips': np.nan
        }

    df = df.sort_values('CloseTime').copy()
    df['CumPips'] = df['Pips'].cumsum()
    df['MaxCumPips'] = df['CumPips'].cummax()
    df['Drawdown'] = df['MaxCumPips'] - df['CumPips']

    wins = df[df['Pips'] > 0]['Pips'].sum()
    losses = df[df['Pips'] < 0]['Pips'].sum()
    pf = wins / abs(losses) if losses < 0 else np.nan
    total_pips = df['Pips'].sum()
    max_dd = df['Drawdown'].max()
    romd = total_pips / max_dd if max_dd > 0 else np.nan
    win_rate = len(df[df['Pips'] > 0]) / len(df) * 100
    avg_pips = df['Pips'].mean()

    return {
        'Label': label,
        'Trades': len(df),
        'WinRate': round(win_rate, 2),
        'PF': round(pf, 3) if not pd.isna(pf) else np.nan,
        'TotalPips': round(total_pips, 1),
        'MaxDD': round(max_dd, 1),
        'RoMD': round(romd, 2) if not pd.isna(romd) else np.nan,
        'AvgPips': round(avg_pips, 2)
    }


def summarize_allowed(df_allowed, df_rejects, group_cols):
    rows = []

    if df_allowed.empty:
        return pd.DataFrame()

    for key, df_g in df_allowed.groupby(group_cols):
        if not isinstance(key, tuple):
            key = (key,)

        label = ' | '.join([str(x) for x in key])
        row = calc_summary(df_g, label)

        for col, val in zip(group_cols, key):
            row[col] = val

        if df_rejects.empty:
            reject_count = 0
        else:
            mask = pd.Series(True, index=df_rejects.index)

            for col, val in zip(group_cols, key):
                mask = mask & (df_rejects[col] == val)

            reject_count = len(df_rejects[mask])

        row['ATRReject'] = reject_count
        row['EntryAllowed'] = row['Trades']
        rows.append(row)

    df_out = pd.DataFrame(rows)

    ordered = group_cols + ['Trades', 'EntryAllowed', 'ATRReject', 'WinRate', 'PF', 'TotalPips', 'MaxDD', 'RoMD', 'AvgPips']
    return df_out[ordered].sort_values(group_cols)

# ==========================================
# 4. ATR validation runner
# ==========================================

def apply_atr_condition(df_base, condition, atr_cache):
    allowed_rows = []
    reject_rows = []

    for _, row in df_base.iterrows():
        decision = get_atr_decision(row['Pair'], row['EntryTime'], condition, atr_cache)

        enriched = row.to_dict()
        enriched.update({
            'ATRCondition': condition['Condition'],
            'UseATR': condition['UseATR'],
            'AtrValue': decision['AtrValue'],
            'AtrThreshold': decision['AtrThreshold'],
            'AtrPercentile': decision['AtrPercentile'],
            'AtrLookback': decision['AtrLookback'],
            'AtrBarTime': decision['AtrBarTime'],
            'AtrReason': decision['AtrReason'],
        })

        if decision['PassATR']:
            allowed_rows.append(enriched)
        else:
            reject_rows.append(enriched)

    return pd.DataFrame(allowed_rows), pd.DataFrame(reject_rows)


def run_atr_validation():
    df_trades = load_trade_log()
    pair_keys = sorted(df_trades['Pair'].unique())
    atr_cache = build_atr_cache(pair_keys)

    all_allowed = []
    all_rejects = []
    comparison_rows = []

    for event_scenario in EVENT_SCENARIOS_TO_TEST:
        df_base = df_trades[df_trades['Scenario'] == event_scenario].copy()
        base_count = len(df_base)

        print('\n' + '=' * 80)
        print(f'▶ Event Scenario: {event_scenario} / Base trades={base_count:,}')
        print('=' * 80)

        for condition in ATR_TEST_CONDITIONS:
            df_allowed, df_rejects = apply_atr_condition(df_base, condition, atr_cache)

            all_allowed.append(df_allowed)
            all_rejects.append(df_rejects)

            row = calc_summary(df_allowed, f"{event_scenario} | {condition['Condition']}")
            row['EventScenario'] = event_scenario
            row['ATRCondition'] = condition['Condition']
            row['BaseEntries'] = base_count
            row['EntryAllowed'] = len(df_allowed)
            row['ATRReject'] = len(df_rejects)
            row['ATRRejectRate'] = round(len(df_rejects) / base_count * 100, 2) if base_count > 0 else np.nan
            comparison_rows.append(row)

            print(
                f"{condition['Condition']}: "
                f"Allowed={len(df_allowed):,}, Reject={len(df_rejects):,}, "
                f"PF={row['PF']}, MaxDD={row['MaxDD']}, TotalPips={row['TotalPips']}"
            )

    df_allowed_all = pd.concat(all_allowed, ignore_index=True) if all_allowed else pd.DataFrame()
    df_rejects_all = pd.concat(all_rejects, ignore_index=True) if all_rejects else pd.DataFrame()
    df_comparison = pd.DataFrame(comparison_rows)

    df_comparison = df_comparison[[
        'EventScenario', 'ATRCondition', 'BaseEntries', 'EntryAllowed', 'ATRReject', 'ATRRejectRate',
        'WinRate', 'PF', 'TotalPips', 'MaxDD', 'RoMD', 'AvgPips'
    ]].sort_values(['EventScenario', 'ATRCondition'])

    df_strategy = summarize_allowed(df_allowed_all, df_rejects_all, ['EventScenario', 'ATRCondition', 'Strategy', 'Pair'])
    df_pair = summarize_allowed(df_allowed_all, df_rejects_all, ['EventScenario', 'ATRCondition', 'Pair'])

    return df_comparison, df_strategy, df_pair, df_allowed_all, df_rejects_all

# ==========================================
# 5. Main
# ==========================================

df_comparison, df_strategy, df_pair, df_allowed, df_rejects = run_atr_validation()

comparison_path = f'{OUTPUT_DIR}/ATRFilter_Comparison_Summary_v1.csv'
strategy_path = f'{OUTPUT_DIR}/ATRFilter_Strategy_Summary_v1.csv'
pair_path = f'{OUTPUT_DIR}/ATRFilter_Pair_Summary_v1.csv'
allowed_path = f'{OUTPUT_DIR}/ATRFilter_Allowed_Trades_v1.csv'
rejects_path = f'{OUTPUT_DIR}/ATRFilter_Rejects_v1.csv'

df_comparison.to_csv(comparison_path, index=False)
df_strategy.to_csv(strategy_path, index=False)
df_pair.to_csv(pair_path, index=False)
df_allowed.to_csv(allowed_path, index=False)
df_rejects.to_csv(rejects_path, index=False)

print('\n' + '=' * 80)
print('🏆 ATR Filter Comparison Summary')
print('=' * 80)
print(df_comparison.to_string(index=False))

print('\n' + '=' * 80)
print('✅ CSV保存完了')
print('=' * 80)
print(f'Comparison Summary: {comparison_path}')
print(f'Strategy Summary  : {strategy_path}')
print(f'Pair Summary      : {pair_path}')
print(f'Allowed Trades    : {allowed_path}')
print(f'ATR Rejects       : {rejects_path}')
